#github repo Actions 이름
name: CI/CD

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

permissions: write-all

jobs:
  build-and-deploy:
  # ubuntu 최신버전에서 실행
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CHECKOUT_TOKEN }}
          submodules: true
          # 자바 버전설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Add permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build -x test

#      - name: Test with Gradle
#        run: ./gradlew --info test
#
#      - name: Publish Unit Test Results
#        uses: EnricoMi/publish-unit-test-result-action@v2
#        if: always()
#        with:
#          junit_files: build/test-results/test/**/*.xml

      # - name: Setup MySQL
      #   uses: samin/mysql-action@v1
      #   with:
      #     mysql database: 'gummymurderer'
      #     mysql user: ${{ secrets.MYSQL_USERNAME }}
      #     mysql password: ${{ secrets.MYSQL_PASSWORD }}
         
      - name: Docker build & push to docker repo
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_REPO }}/directors-dev .
          docker push ${{ secrets.DOCKER_REPO }}/directors-dev

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        id: deploy
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PEMKEY }}
          envs: GITHUB_SHA
          script: |
            sudo docker stop spring-server-container
            sudo docker rm spring-server-container
            sudo docker pull ${{ secrets.DOCKER_REPO }}/directors-dev
            sudo docker run --name spring-server-container -d -p 8081:8081 gummymurderer/directors-dev
            sudo docker image prune -f
